baseURL = "/"
languageCode = "en-gb"

title = "My PhD Code"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "Links"
sidebarColor = "default"
customCss = []

[[menu.shortcuts]]
name = "Data"
url = "https://www.dropbox.com/sh/pkn7b4xxseytok3/AAAcrs8hd5DnvS8YLl_101uBa?dl=0"
weight = 9

[[menu.shortcuts]]
name = "My PhD website"
url = "http://phd.haziqj.ml"
weight = 10

[[menu.shortcuts]]
name = "My PhD thesis"
url = "https://github.com/haziqj/phd-thesis/"
weight = 11

[[menu.shortcuts]]
name = "My website"
url = "https://haziqj.ml"
weight = 12

[[menu.shortcuts]]
name = "R/iprior"
url = "https://github.com/haziqj/iprior"
weight = 13

[[menu.shortcuts]]
name = "R/iprobit"
url = "https://github.com/haziqj/iprobit"
weight = 14

[[menu.shortcuts]]
name = "R/ipriorBVS"
url = "https://github.com/haziqj/ipriorBVS"
weight = 15


